Make sure that the `tars` list contains unique records
There is no garantee that the OCI Manifest layers record contains only
unique items. In case there is a duplicity, `bazel` complains that
`srcs` for `blog` target contains duplicities. Therefore, we need to
be sure that there is no such duplicities in `tars` list.

Example of error message:

```
ERROR: /beyond/.bazel_cache/external/test_image_single/BUILD.bazel:43:18: Label '@test_image//:4f4fb700ef54461cfa02571ae0db9a0dc1e0cdb5577484a6d75e68dc38e8acc1' is duplicated in the 'srcs' attribute of rule 'blobs'
```